---

- name: Create InfluxDB repository configuration file
  copy:
    content: |
      [influxdb]
      name = InfluxDB Repository
      baseurl = https://repos.influxdata.com/rhel/7/x86_64/stable/
      enabled = 1
      gpgcheck = 0
      gpgkey = https://repos.influxdata.com/influxdb.key
    dest: /etc/yum.repos.d/influxdb.repo

- name: Install InfluxDB
  yum:
    name: influxdb
    state: present

- name: Start the InfluxDB service
  systemd:
    name: influxdb
    state: started
    enabled: yes

- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/enterprise/release/grafana-enterprise-9.2.2-1.x86_64.rpm
    dest: /tmp/grafana-enterprise-9.2.2-1.x86_64.rpm

- name: Install Grafana
  yum:
    name: /tmp/grafana-enterprise-9.2.2-1.x86_64.rpm

- name: Enabling Grafana service
  service:
    name: grafana-server
    enabled: yes

- name: Modifying service file
  tags: es_ubuntu
  replace:
    path: /usr/lib/systemd/system/grafana-server.service
    regexp: "TimeoutStartSec=75"
    replace: "TimeoutStartSec=500"

- name: Enable/Start Grafana
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Creating a directory (downloaded files will be stored)
  tags: directory
  file:
    path: ~/prometheus
    state: directory

- name: Downloading and extracting Prometheus
  tags: source
  unarchive:
    src: "{{source}}"
    dest: ~/prometheus
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Stopping the service
  service:
    name: snap.prometheus.prometheus.service
    state: stopped

- name: Adding the Prometheus executables to a PATH
  tags: executables
  shell: |
    cd ~/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus
  ignore_errors: yes

- name: Copying the Prometheus service file
  tags: servicefile
  copy:
    src: /etc/systemd/system/snap.prometheus.prometheus.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 777
    remote_src: yes

- name: Making the Prometheus is started and enabled
  tags: serviceon
  service:
    name: snap.prometheus.prometheus.service
    state: restarted
    enabled: true

